export const SET_DATA = "SET_DATA"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const PRICE_UPDATE = "PRICE_UPDATE"

export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY"

export const CHECK_FORM_DETAILS = "CHECK_FORM_DETAILS"
export const SET_FORM_DETAILS = "SET_FORM_DETAILS"
export const GET_FORM_DETAILS = "GET_FORM_DETAILS"

export const UPDATE_DETAIL_START = "UPDATE_DETAIL_START"
export const UPDATE_FORM_DETAILS = "UPDATE_FORM_DETAILS"
export const UPDATE_DETAIL_END = "UPDATE_DETAIL_END"